language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make test_xunit

after_success:
  - make docker_build
deploy:
  provider: heroku
  app: tranquil-inlet-80379
  api_key: ${HEROKU_API_KEY}
